name: Build, Test and Publish Nuget Package

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  publish_nuget_package:
    runs-on: ubuntu-latest
    env:
      CSPROJ_PATH: ./src/dol.IoT.Models/dol.IoT.Models.csproj

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore $CSPROJ_PATH
      - name: Build
        run: dotnet build $CSPROJ_PATH --no-restore --configuration Release
      - name: Test
        run: dotnet test --verbosity normal
      - name: Pack
        run: dotnet pack $CSPROJ_PATH --no-restore --no-build
      - name: Publish
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
          SERVICE_INDEX: https://api.nuget.org/v3/index.json
          NUGET_PATH: "/home/runner/work/**.nupkg"
        run: dotnet nuget push $NUGET_PATH --api-key $API_KEY -s $SERVICE_INDEX
